export const Foods = [
  {
    name: 'Belo meso piletina',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 0,
      fats: 3,
      proteins: 31,
      calories: 116,
    },
  },
  {
    name: 'Protein',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 0,
      fats: 0,
      proteins: 100,
      calories: 400,
    },
  },
  {
    name: 'Hidrat',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 100,
      fats: 0,
      proteins: 0,
      calories: 400,
    },
  },
  {
    name: 'Mast',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 0,
      fats: 100,
      proteins: 0,
      calories: 900,
    },
  },
  {
    name: 'Maksi hleb',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 37.5,
      fats: 6.6,
      proteins: 8.1,
      calories: 259,
    },
  },
  {
    name: 'Jaje',
    quantity: 70,
    unit: 'g',
    nutrients: {
      carbs: 0.3,
      fats: 6.3,
      proteins: 8.6,
      calories: 92,
    },
  },
  {
    name: 'Humus',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 8,
      fats: 23,
      proteins: 8,
      calories: 285,
    },
  },
  {
    name: 'Barila intergalna testenina',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 64,
      fats: 2.5,
      proteins: 13,
      calories: 347,
    },
  },
  {
    name: 'Pirinac intergalni (Bianchi)',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 71.5,
      fats: 2.4,
      proteins: 7,
      calories: 347,
    },
  },
  {
    name: 'Kackavalj gauda',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 0.4,
      fats: 26.5,
      proteins: 25.3,
      calories: 341,
    },
  },
  {
    name: 'Crna cokolada UGANDA',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 25,
      fats: 48,
      proteins: 8.5,
      calories: 590,
    },
  },
  {
    name: 'kikiriki Gud Diet',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 10.2,
      fats: 49.5,
      proteins: 29.5,
      calories: 618,
    },
  },
  {
    name: 'Tunjevina La Perla',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 0.1,
      fats: 19.7,
      proteins: 16.3,
      calories: 243,
    },
  },
  {
    name: 'Svinjski vrat',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 0,
      fats: 23,
      proteins: 16.5,
      calories: 267,
    },
  },
  {
    name: 'Junetina',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 0,
      fats: 5.5,
      proteins: 21.5,
      calories: 142,
    },
  },
  {
    name: 'Krompir svez',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 17.5,
      fats: 0,
      proteins: 2,
      calories: 77,
    },
  },
  {
    name: 'Pileci batak sa koskom i kozicom svez',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 0,
      fats: 2,
      proteins: 5,
      calories: 45,
    },
  },
  {
    name: 'Ovsene pahuljice',
    quantity: 100,
    unit: 'g',
    nutrients: {
      carbs: 60,
      fats: 6,
      proteins: 14,
      calories: 370,
    },
  },
];
